### ISSUE TITLE
Optimize peerDependencies of the react-ai-sdk package

### ISSUE THREAD

**Issue by juagonala** [Yonom/assistant-ui#1004]
Hi there,

I noticed you are including the `ai` NPM dependency in the `react-ai-sdk` package.

https://github.com/Yonom/assistant-ui/blob/b3991bf304501e7fcd12d8f1de6e961814056543/packages/react-ai-sdk/package.json#L37

As long as the project is focused on React, please, consider replacing it with the `@ai-sdk/react` package.
This way, you can remove unnecessary dependencies for other frameworks like **Vue**, **Svelte**, **Solid**, etc. included in the `ai` package.

I know this change will also remove all LLM providers, but we can include only those we use like `@ai-sdk/openai`.

Thanks in advance.

**Comment by Yonom** [comment]
fixed in  v0.6.13
