### ISSUE TITLE
Langgraph streaming error

### ISSUE THREAD

**Issue by eniola-enilolobo** [Yonom/assistant-ui#1005]
Hello, I'm trying to hook up assistant UI to langraph but recently started getting an error that affected the behavior of the frontend application. I never got this error in the past. I just started up my FE and BE servers one day and noticed this.

Here's a screenshot of the error in my browser console: 
![image](https://github.com/user-attachments/assets/1c1d199c-e7dc-4508-a42d-eca8eeb5e977)

**Comment by Yonom** [comment]
Thanks for reporting this, fixed in v0.0.21

**Comment by eniola-enilolobo** [comment]
Thanks for the feedback...all good now.
