### ISSUE TITLE
Thread Switching between sessions

### ISSUE THREAD

**Issue by musafurkanzenbilci** [Yonom/assistant-ui#1018]
Hi @Yonom ,

I was creating a prototype for a chatbot and this repo saved me so much time. Thanks for the effort. But now I need one more level of advancement and can't seem to find how to do it. I want to add different sessions, show them in a sidebar, and switch between them just like ChatGPT. I am using my own REST-API with a custom RuntimeProvider so I can handle the switch in the agent by myself. The problem here I could not pass in the appropriate message list to the Thread. I saw the Decomposition section in the docs but could not find where to pass in the messages and in which format.

How and where should I pass in the `messages` prop to?

This is the decomposed Thread
```tsx
import {
    Thread,
    ThreadWelcome,
    Composer,
    type ThreadConfig,
  } from "@assistant-ui/react";
  import { FC, useCallback } from "react";

export const MyThread: FC<ThreadConfig> = (config, messages) => {
    return (
        <Thread.Root config={config}>
        <Thread.Viewport>
            <ThreadWelcome />
            <Thread.Messages/>
            <Thread.FollowupSuggestions />
            <Thread.ViewportFooter>
            <Thread.ScrollToBottom />
            <Composer />
            </Thread.ViewportFooter>
        </Thread.Viewport>
        </Thread.Root>
    );
  }
```

and this is the Assistant I am using

```tsx
"use client";

import { Thread } from "@assistant-ui/react";
import { MyThread } from "@/components/MyThread";
import { makeMarkdownText } from "@assistant-ui/react-markdown";

const MarkdownText = makeMarkdownText();

export function MyAssistant(messages) {
  return (
    <MyThread
      assistantMessage={{ components: { Text: MarkdownText } }}
      messages={messages}
    />
  );
}

```

**Comment by Yonom** [comment]
Hey, the messages are managed by the runtime, so you have to pass it to your runtime. For example:

```ts
const runtime =useLocalRuntime({ initialMessages: ... });

// or if you want to set it later:
const loadMessages = () => {
  const messages = fetch(messages from your storage);
  runtime.reset({ initialMessages: messages });
};
```

I hope this help!

**Comment by musafurkanzenbilci** [comment]
Thanks it helps

**Comment by Tolsto** [comment]
@Yonom How would I add custom metadata to the `initialMessages`? As far as I can tell, there is currently no way to restore messages with custom metadata?
