### ISSUE TITLE
Artifacts on the way?

### ISSUE THREAD

**Issue by RobertHH-IS** [Yonom/assistant-ui#1020]
Hi, 
Are artifacts on the way?  At the moment it is just an iframe to a vercel demo page.  
Is there a ETA for it as it would be really useful?

**Comment by Yonom** [comment]
Hey, the source code can be found here:
https://github.com/Yonom/assistant-ui-artifacts

How can I make it better for you?

**Comment by Yonom** [comment]
Closed as resolved for now
