### ISSUE TITLE
Translate or internationalization

### ISSUE THREAD

**Issue by raphaguasta** [Yonom/assistant-ui#1021]
Hello guys!

Amazing project, congrats!
I want to change the language of default components, like "How can I help you today?".

I didn't find how to do it, there's a way?

Thanks!

**Comment by Yonom** [comment]
Hey, yes, there is a way, but help to integrate the package into an i18n library is greatly appreciated.

The strings are found as follows:

```
<Thread
  welcome={{ message: "How can I help you today?" }}
  strings={{ /* all the other strings are here */ }}
```

I just went ahead and added the default Thread welcome message to the `strings` config as well, this will be released in the next version. This way, you just have to translate the keys inside the strings={} object

I hope this helps! I would love to maintain the strings config for other languages, in case you end up creating one, that would be greatly appreciated!

**Comment by Yonom** [comment]
Closing this, let me know if you have any feedback
