### ISSUE TITLE
Attachment of pdf or docs

### ISSUE THREAD

**Issue by SushekTamrakar** [Yonom/assistant-ui#1029]
`import { useEdgeRuntime } from "@assistant-ui/react";
import {
  CompositeAttachmentAdapter,
  SimpleImageAttachmentAdapter,
  SimpleTextAttachmentAdapter,
} from "@assistant-ui/react";
 
const runtime = useEdgeRuntime({
  api: "/api/chat",
  adapters: {
    attachments: new CompositeAttachmentAdapter([
      new SimpleImageAttachmentAdapter(),
      new SimpleTextAttachmentAdapter(),
    ]),
  },
});`

I can't find a way to attach the pdf and docs, is there a possible way to do so? This above code just support images and text

**Comment by Yonom** [comment]
Hello! You will need to integrate with a service that handles parsing PDFs and docs. Native support for this is coming soon, in the meantime, you can look into implementing your own AttachmentAdapter and integrate with a service like LlamaParse

**Comment by SushekTamrakar** [comment]
sure thank you.
