### ISSUE TITLE
Dark mode using media selector

### ISSUE THREAD

**Issue by igo** [Yonom/assistant-ui#1030]
Please add support for media selector darkMode instead of class.

**Comment by Yonom** [comment]
Hello, 

thanks for raising this issue. I will look into adding native support for this in the library.

In the meantime - please do the following:

1. copy the theme: https://github.com/Yonom/assistant-ui/blob/main/packages/react/src/styles/themes/default.css
2. paste it to your `globals.css`
3. update the dark mode CSS selector

Hope this helps!

Best
Simon
