### ISSUE TITLE
Cannot see text in Dark Mode Playground 

### ISSUE THREAD

**Issue by abhirupghosh** [Yonom/assistant-ui#1097]
Images attached.
<img width="1512" alt="Screenshot 2024-10-26 at 1 22 55 PM" src="https://github.com/user-attachments/assets/cf908243-47f5-4867-b9af-ede1d62e4167">
<img width="1512" alt="Screenshot 2024-10-26 at 1 22 46 PM" src="https://github.com/user-attachments/assets/0a9bcd67-1cea-4509-bfcd-20f8fe77582b">

**Comment by Yonom** [comment]
Thank you for reporting this! fixing...

**Comment by Yonom** [comment]
The bug has been fixed, I will work with helicone to push this live

**Comment by Yonom** [comment]
Issue is being tracked on the Helicone repository

https://github.com/Helicone/helicone/pull/2896

**Comment by Yonom** [comment]
@abhirupghosh fix is deployed on helicone
