### ISSUE TITLE
Add support for changing headers on the fly

### ISSUE THREAD

**Issue by igo** [Yonom/assistant-ui#1110]
Hi, would it be possible to define headers sent by useEdgeRuntime to backend before each call? 

Maybe something like this so that I could use different value each time. Would this work?
```ts
const [myHeader, setMyHeader] = useState(...);
const runtime = useEdgeRuntime({
  headers: () => ({ 'x-my-header': myHeader }),
});
```

**Comment by Yonom** [comment]
There is the following trick you can already use to get the same effect:

```ts
const runtime = useEdgeRuntime({
  headers: { 
    get 'x-my-header'() {
      return myHeader
    },
  },
});

Let me know if you are hitting any limits from this approach and I can consider adding something

**Comment by benedict-jackson** [comment]
This doesn't work if getting the token requires calling an async function, unless I'm not being creative enough.
