### ISSUE TITLE
Langgraph cloud: Support for File Upload/attachments

### ISSUE THREAD

**Issue by bepisorconk** [Yonom/assistant-ui#1137]
Looks like there isn't any support for file attachments in Langgraph runtime for now. Is this in the roadmap?

**Comment by Yonom** [comment]
Hey, we currently have experimental image upload support via setting `unstable_allowImageAttachments` in `useLangGraphRuntime`. Other attachments support is coming soon

**Comment by Yonom** [comment]
Hey @bepisorconk, you can now add an attachment adapter as documented here:

https://www.assistant-ui.com/docs/guides/Attachments

which supports both files and images
