### ISSUE TITLE
shadcn-ui CLI deprecated

### ISSUE THREAD

**Issue by haaln** [Yonom/assistant-ui#1139]
### Issue and Steps to Reproduce
Following the instructions for adding assistant-ui with shadcn according to the [docs](https://www.assistant-ui.com/docs/ui/shadcn-ui/Thread) doesn't work because [shadcn-ui cli is deprecated](https://www.npmjs.com/package/shadcn-ui)

### Versions
assistant-ui@0.0.18

#### Steps to reproduce
`npx shadcn-ui@latest init`
Produces an error `sh: line 1: shadcn-ui: command not found`

#### Expected
Adds `/components/ui/assistant-ui/thread.tsx` along with other components.

#### Workaround fix
`git clone https://github.com/Yonom/assistant-ui.git && cd assistant-ui`
`find . -type f -exec sed -i 's/shadcn-ui/shadcn/g' {} \;` 
change dependency of shadcn `./packages/cli/package.json` (prepend a ^)
`npm install .`
Then just take the components you want to your project folder. 

So far haven't seen any unintended consequences for such a crude method but if anyone else has the same problem this is the workaround until someone does a proper fix.

**Comment by Yonom** [comment]
The correct command would be `npx shadcn@latest init`. I updated the docs just now, let me know if this fixes it

**Comment by haaln** [comment]
Thanks for the update, but I realize that I may have been unclear in reporting the steps to reproduce the bug.

I realized initially that I needed to run `npx shadcn@latest init` due to the deprecation, but running the following command `npx assistant-ui@latest add thread` causes:

`Configuration is missing. Please run npx shadcn-ui init to create a components.json file.`

hence the roundabout fix of cloning the repo and replacing all instances of 'shadcn-ui' inside the files.

**Comment by Yonom** [comment]
Thank you for reporting this! I have now adopted the new shadcn CLI for the `add` command. Let me know if you're still experiencing issues!
