### ISSUE TITLE
Composer attachment not present

### ISSUE THREAD

**Issue by utkarsh-alpuria** [Yonom/assistant-ui#1158]
Tried following the composer.attachments in dcomposition section of the documentation
**LINK** - https://www.assistant-ui.com/docs/ui/styled/Decomposition#composer

**ERROR:** '"@assistant-ui/react"' has no exported member named 'ComposerAttachment'. Did you mean 'CompleteAttachment'?
**CODE:**
import { FC } from "react";
import { Composer, ThreadPrimitive } from "@assistant-ui/react";
 

import { ComposerAttachment } from "@assistant-ui/react";
 
const MyComposerAttachment: FC = () => {
  return (
    <ComposerAttachment.Root>
      attachment
      <ComposerAttachment.Remove />
    </ComposerAttachment.Root>
  );
};

export const MyComposer: FC = () => {
  return (
    <Composer.Root>
      <Composer.Attachments />
      <Composer.AddAttachment />
      <Composer.Input autoFocus />
      <Composer.Action />
    </Composer.Root>
  );
};

Initially tried ThreadWelcome.Message and ThreadWelcome.suggestions, it worked but not exactly how it was mentioned in the documentation

**VERSIONS USING**
    "@assistant-ui/react": "^0.7.0",
    "@assistant-ui/react-markdown": "^0.7.0",

**FILE STRUCTURE IMAGE**
<img width="761" alt="Composer_attachments_error" src="https://github.com/user-attachments/assets/6bb3f38f-ef63-4038-a7ca-2c809ed5e544">

**Comment by Yonom** [comment]
Thanks a lot for reporting this, `ComposerAttachment` was renamed to `AttachmentUI` because it is also used for MessageAttachments

**Comment by Yonom** [comment]
I opened this issue to track the progress towards making AttachmentUI's decomposition have feature parity with the default UI

https://github.com/Yonom/assistant-ui/issues/1160

**Comment by utkarsh-alpuria** [comment]
Thank you for your response @Yonom , I tried editing the code accordingly and got a different error.

**ERROR**
Unhandled Runtime Error
Error: This component must be used within a ComposerPrimitive.Attachments or MessagePrimitive.Attachments component.

**CODE**

import { FC } from "react";
import { Composer, ThreadPrimitive } from "@assistant-ui/react";
 
 

import { AttachmentUI } from "@assistant-ui/react";
 
const MyAttachmentUI: FC = () => {
  return (
    <AttachmentUI.Root>
      attachment
      <AttachmentUI.Remove />
    </AttachmentUI.Root>
  );
};


export const MyComposer: FC = () => {
  return (
    <Composer.Root>
      <MyAttachmentUI />
      <Composer.AddAttachment />
      <Composer.Input autoFocus />
      <Composer.Action />
    </Composer.Root>
  );
};
