### ISSUE TITLE
Unable to stop/cancel the running process

### ISSUE THREAD

**Issue by isnl** [Yonom/assistant-ui#1173]
![image](https://github.com/user-attachments/assets/7811cff0-5ecb-41cd-a3c7-9e2138b361db)

Hello, when I use this example, I notice there is no stop/cancel button, and I cannot stop the process.

Here's what it looks like:

![image](https://github.com/user-attachments/assets/d3a2aa07-b08c-42b4-8f5d-e789fb5b1630)

It uses the Thread component

-----------------------------------

However, when I tried this approach, it doesn't work either:

<img width="617" alt="image" src="https://github.com/user-attachments/assets/14ca906e-6b08-4daf-b549-3613f9103176">

I don't know why, please help me

**Comment by Yonom** [comment]
Hey, React Server Components do not support cancellation. Do not use RSC if you care about cancellation

see also: https://sdk.vercel.ai/docs/ai-sdk-rsc/migrating-to-ui

**Comment by isnl** [comment]
ok, I know.Thank you!
