### ISSUE TITLE
Unable to import useThreadEmpty and other hooks from the @assistant-ui/react package

### ISSUE THREAD

**Issue by dmagunov** [Yonom/assistant-ui#1205]
Hi, thanks for creating this great library. When I try to import `useThreadEmpty` as mentioned in the [documentation](https://www.assistant-ui.com/docs/ui/primitives/Thread#empty), it fails because [primitive-hooks/index.ts](https://github.com/Yonom/assistant-ui/blob/main/packages/react/src/primitive-hooks/index.ts) doesn't export this hook.

@assistant-ui/react: 0.7.7

**Comment by Yonom** [comment]
Thanks a lot for reporting this. those hooks were a previous feature that is no longer available.

To check if a thread is empty you can now do

```ts
const isEmpty = useThread(t => t.messages.length === 0);
```
