### ISSUE TITLE
bug: Missing CommonJS compilation artifacts

### ISSUE THREAD

**Issue by j-cordoba-gs** [Yonom/assistant-ui#1230]
I was trying to unit test my components after decomposition. But as soon as the test runs it fails with this message:

    Test suite failed to run
    Cannot find module './api/index.cjs' from 'node_modules/@assistant-ui/react/dist/index.js'

    Require stack:
      node_modules/@assistant-ui/react/dist/index.js
      src/components/Chatbot/components/ThreadWelcome.tsx
      src/components/Chatbot/Chatbot.tsx
      src/components/Chatbot/tests/Chatbot.test.tsx

I checked the main index.js file in the dist folder and it tries to import these .cjs files:

    // src/index.ts
    var src_exports = {};
    __export(src_exports, {
      INTERNAL: () => INTERNAL
    });
    module.exports = __toCommonJS(src_exports);
    __reExport(src_exports, require("./api/index.cjs"), module.exports);
    __reExport(src_exports, require("./context/index.cjs"), module.exports);
    __reExport(src_exports, require("./model-config/index.cjs"), module.exports);
    __reExport(src_exports, require("./primitive-hooks/index.cjs"), module.exports);
    __reExport(src_exports, require("./primitives/index.cjs"), module.exports);
    __reExport(src_exports, require("./runtimes/index.cjs"), module.exports);
    __reExport(src_exports, require("./types/index.cjs"), module.exports);
    __reExport(src_exports, require("./ui/index.cjs"), module.exports);
    var INTERNAL = __toESM(require("./internal.cjs"));
    // Annotate the CommonJS export names for ESM import in node:
    0 && (module.exports = {
      INTERNAL,
      ...require("./api/index.cjs"),
      ...require("./context/index.cjs"),
      ...require("./model-config/index.cjs"),
      ...require("./primitive-hooks/index.cjs"),
      ...require("./primitives/index.cjs"),
      ...require("./runtimes/index.cjs"),
      ...require("./types/index.cjs"),
      ...require("./ui/index.cjs")
    });

But no .cjs file exists in the repo, they are all .js instead.

Thank you!

**Comment by Yonom** [comment]
Thanks a lot for reporting this!

**Comment by Yonom** [comment]
related bug 

https://github.com/favware/esbuild-plugin-file-path-extensions/pull/153

**Comment by Yonom** [comment]
@j-cordoba-gs fixed in @assistant-ui/react@0.7.9
