### ISSUE TITLE
Loading initial messages doesn't set thread state to `regular`

### ISSUE THREAD

**Issue by Tolsto** [Yonom/assistant-ui#1244]
When using runtime with `initialMessages` the thread state will remain `new` until an additional message gets added to the thread. As a result, the `reset()` action has no effect as it will not switch to a new thread.

Tested with 0.7.11

**Comment by Yonom** [comment]
thank you! this is a great bug report

**Comment by Yonom** [comment]
This should be fixed in the most recent version, since `import` now triggers a thread initialization!
