### ISSUE TITLE
How to configure the proxy 

### ISSUE THREAD

**Issue by xiaomayi-ant** [Yonom/assistant-ui#1250]
We followed the tutorial for installation and testing, but encountered an error. After troubleshooting, we believe the issue is due to not setting up a proxy. However, we are unsure how to modify the file to create a proxy. Therefore, we would appreciate your assistance. Thank you!
<img width="1417" alt="proxy" src="https://github.com/user-attachments/assets/cb3b933e-40f3-4a95-9258-ed0390af6372" />

**Comment by Yonom** [comment]
Hey, this is a repository which has the proxy set up:

https://github.com/yonom/assistant-ui-starter

In particular, please check the /app/api/chat/route.ts file

Let me know if the issue continues to persist

**Comment by xiaomayi-ant** [comment]
Thank you for your reply. After multiple attempts, we finally resolved the proxy issue by using a server in the United States. We also want to express our gratitude for your project, as it has greatly facilitated our work. Once again, thank you!



---- Replied Message ----
| From | Simon ***@***.***> |
| Date | 12/18/2024 16:17 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Yonom/assistant-ui] How to configure the proxy (Issue #1250) |

Hey, this is a repository which has the proxy set up:

https://github.com/yonom/assistant-ui-starter

In particular, please check the /app/api/chat/route.ts file

Let me know if the issue continues to persist
