### ISSUE TITLE
console.log(this.contentBinding); is not removed from the code.

### ISSUE THREAD

**Issue by hiroaki2020** [Yonom/assistant-ui#1256]
I am using assistant-ui with useAssistant and browser console continues to receive output from ```console.log(this.contentBinding);```
Output is object called ```ShallowMemoizeSubject```.

relavant files and lines are 
```
ContentPartRuntime.mjs:16
```

**Comment by Yonom** [comment]
@hiroaki2020 thanks for reporting this! can you try upgrading assistant-ui?

```ts
npm i @assistant-ui/react@latest
```

**Comment by hiroaki2020** [comment]
The logs are gone now!
Thank you so much!
