### ISSUE TITLE
Error: MessageRepository(performOp/link): A message with the same id already exists in the parent tree. This error occurs if the same message id is found multiple times. This is likely an internal bug in assistant-ui.

### ISSUE THREAD

**Issue by n-sviridenko** [Yonom/assistant-ui#1261]
Happens at random moments when integrated with the LangGraph runtime:

<img width="1009" alt="Screenshot 2024-12-20 at 12 56 34" src="https://github.com/user-attachments/assets/360964d9-eb3c-45d1-9739-657534cbe603" />

The code is the same as in https://www.assistant-ui.com/docs/runtimes/langgraph

**Comment by Yonom** [comment]
Oh no! This error only happens if two messages in your langgraph messages list have the exact same ID

Are you perhaps appending the same message ID twice?

**Comment by n-sviridenko** [comment]
@Yonom not really..

**Comment by n-sviridenko** [comment]
I'll try debugging once it appears again and get back. Will see what kind of messages are duplicated.

**Comment by n-sviridenko** [comment]
Never happened again
