### ISSUE TITLE
Markdown error: React does not recognize the `componentsByLanguage` prop on a DOM element.

### ISSUE THREAD

**Issue by ifreeman6** [Yonom/assistant-ui#1265]
When I integrate the `@assistant-ui/react-markdown`, occurs this error when show markdown text in the page.

```
React does not recognize the `componentsByLanguage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `componentsbylanguage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

this is my dependencies:

```
  "dependencies": {
    "@ai-sdk/openai": "^1.0.7",
    "@assistant-ui/react": "^0.7.17",
    "@assistant-ui/react-markdown": "^0.7.5",
    "next": "15.1.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.23.8"
  },
```

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the MarkdownTextPrimitive component to properly handle the componentsByLanguage prop and prevent it from being passed to the DOM element. This fixes the React warning about unrecognized props on DOM elements.

You can review changes in this commit: https://github.com/wwqwq2313/Yonom-assistant-ui-1265/commit/c5181ba67b7e754511761d88ff8a2788420eaa9b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Yonom** [comment]
Fixing...
