### ISSUE TITLE
bug(cli): `npx assistant-ui add thread` fails on Windows

### ISSUE THREAD

**Issue by frankdagostino** [Yonom/assistant-ui#182]
Hi Yonom,

i'm not able to add assistant-ui to my project:

npx assistant-ui add thread
Error: spawn npx ENOENT
other-package-script process exited with code -4058

Thank you,
Frank

**Comment by Yonom** [comment]
Hey Frank, thanks for reaching out!

I believe the error you're encountering is because the `npx` command cannot be found.  

`npx` is part of Node.js. Do you have Node.js installed?

If you have node installed, make sure it is in your PATH. 

Can you try running the following commands and report back?
```sh
npx --version
node --version
```

**Comment by Yonom** [comment]
Hey Frank, thanks a lot for reporting this.

I can reproduce the error and will work on a fix.

In the meantime, you can use the following command as a workaround:

```sh
set COMPONENTS_REGISTRY_URL=https://www.assistant-ui.com && npx shadcn-ui add thread
```
or for powershell
```sh
$env:COMPONENTS_REGISTRY_URL="https://www.assistant-ui.com"; npx shadcn-ui add thread
```

**Comment by frankdagostino** [comment]
ok, added now but can't compile:
![image](https://github.com/Yonom/assistant-ui/assets/38862585/5c1e4a6d-6a5f-412f-88f0-e197bf6f4c3d)

**Comment by Yonom** [comment]
Thanks a lot for the report. I will also fix that.

In the meantime, you can install the `ai` package manually. 

```
npm install ai
```

**Comment by Yonom** [comment]
Note that you also need to setup a runtime to connect the UI components to an LLM such as OpenAI's GPT-4o.
https://www.assistant-ui.com/docs/runtimes/vercel-ai-sdk-ui/use-chat

Those instructions will also tell you to install the `ai` package. But the error you are getting is nonetheless unexpected, sorry about that.

**Comment by frankdagostino** [comment]
Ok, installed the 'ai' package.

![image](https://github.com/Yonom/assistant-ui/assets/38862585/1ae14d0e-5a48-416f-8118-02f2e31e6afc)

Is there any chance to use just the UI components without all this 'ai stuff' ? I've my AI services, and i I dont need the whole end to end AI integration, i would just like to add your wonderfull UI components in my project ( expecially the modal one )! 

Thank you in advance!
Frank

**Comment by Yonom** [comment]
You need some sort of `Runtime` to power the UI...

If you already have your own backend, you can use that to power `assistant-ui`.

Here's a minimal non-AI runtime to get you started :) 

```ts
import {
  AssistantRuntimeProvider,
  type unstable_ChatModelAdapter as ChatModelAdapter,
  unstable_useLocalRuntime as useLocalRuntime,
} from "@assistant-ui/react";

const MyLocalModelAdapter: ChatModelAdapter = {
  async run({ messages, abortSignal }) {
    // add your own API here
    const result = await fetch("YOUR API HERE", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      // forward the messages in the chat to the API
      body: JSON.stringify({
        messages,
      }),
      // if the user hits the "cancel" button or escape keyboard key, cancel the request
      signal: abortSignal,
    });

    const data = await result.json();
    return {
      content: [
        {
          type: "text",
          text: data.text,
        },
      ],
    };
  },
};

const MyRuntimeProvider = ({ children }: { children: React.ReactNode }) => {
  const runtime = useLocalRuntime(MyLocalModelAdapter);
  return (
    <AssistantRuntimeProvider runtime={runtime}>
      {children}
    </AssistantRuntimeProvider>
  );
};
```

And then wrap your app in `MyRuntimeProvider`.

**Comment by Yonom** [comment]
@frankdagostino I would love to learn more about what you're building. Would you be open to a brief call?

You can book something here https://cal.com/simon-farshid :)

**Comment by frankdagostino** [comment]
@Yonom thanks for your time!

I'm mainly a backend developer and I already have my personal AI services. Your suggestion is is exatly what I need.

This is ay actual situation on my nextjs project:

**Layout**
`export default function Layout({ children }: { children: React.ReactNode }) {
  return (
  ...
          <CustomRuntimeProvider>{children}</CustomRuntimeProvider></div>
...
  );
}`

**CustomRuntimeProvider**
`import {
    AssistantRuntimeProvider,
    type unstable_ChatModelAdapter as ChatModelAdapter,
    unstable_useLocalRuntime as useLocalRuntime,
} from "@assistant-ui/react";


const CustomModelAdapter: ChatModelAdapter = {
    async run({ messages, abortSignal }) {
        return {
            content: [
                {
                    type: "text",
                    text: 'ai response',
                },
            ],
        };
    },
};

export const CustomRuntimeProvider = ({ children }: { children: React.ReactNode }) => {
    const runtime = useLocalRuntime(CustomModelAdapter);
    return (
        <AssistantRuntimeProvider runtime={runtime}>
            {children}
        </AssistantRuntimeProvider>
    );
};`

**test page**
`'use client'
import { AssistantModal } from "@/components/ui/assistant-ui/assistant-modal";

export default function AssistantUi() {
    return (
        <div className="h-full">
            <AssistantModal />
        </div>
    );
}`

**Comment by Yonom** [comment]
@frankdagostino at the top of the CustomRuntimeProvider, you want to add "use client"; (just like in the test page), then you should be good

**Comment by Yonom** [comment]
@frankdagostino there was another bug that would prevent the example above from working; which I just fixed. So please update assistant-ui in package.json to "0.0.26", then run "npm install" to install the update

Here is a working demo: (I took your example and added "use client" and updated "@assistant-ui/react" to "0.0.26"
https://github.com/Yonom/assistant-ui-custom-api

<img width="416" alt="image" src="https://github.com/Yonom/assistant-ui/assets/1394504/4eee2f8c-af27-4d23-975b-6612e15bfa5a">
