### ISSUE TITLE
Support for `addResult` When using `useLocalRuntime`

### ISSUE THREAD

**Issue by Rajaniraiyn** [Yonom/assistant-ui#459]
The current implementation of the assistant-ui repo lacks support for the addResult function when utilizing the useLocalRuntime feature. This limitation restricts the ability to dynamically add results during runtime operations, impacting the flexibility and functionality of local runtime scenarios.

Expected Behavior:
- The addResult function should be fully supported when useLocalRuntime is enabled.
- Users should be able to dynamically add results during local runtime execution without encountering errors or limitations.

**Comment by Yonom** [comment]
@Rajaniraiyn Thanks!

v0.4.3 adds supports for this!
