### ISSUE TITLE
Initial Message from Assistant Causing Re-renders and Multiple Unnecessary API Calls

### ISSUE THREAD

**Issue by kartikp36** [Yonom/assistant-ui#629]
## Description:
I am trying to implement an initial welcome message from the chatbot in a project using the assistant-ui with Vercel AI SDK in useChat Runtime. The goal is for the chatbot to start the conversation after a 5-second timeout upon website loading. However, the implementation is causing multiple re-renders and unnecessary API calls.
## Steps to Reproduce:
- Use the initialMessages property to set up the initial welcome message.
` initialMessages: [{
      id: "1",
      content: "Hello",
      role: "assistant",
    }]`
    
    Or by:
`const append = useAppendMessage();`
`append({ role: "assistant", content: [{ type: "text", text: "Hi, how can I help you?" }] }); `
[My code for reference](https://github.com/Yonom/assistant-ui/commit/6d83b9158aef9237905e551de96972457c7a8ce7)

[Observe](https://flonnect.com/video/956de37a3c24-4bcc-b049-1e1cbfd6b593) that the property works but leads to multiple re-renders and unnecessary API calls also leading to an abrupt suggestion text change.

**Comment by kartikp36** [comment]
Here's a possible workaround:
### Solution:
1. Memoization: I used memoization to ensure that suggestions only render when assistant messages update in thread.tsx.
2. Debounce: I added a simple debounce of 1000ms for calling the handleClick() callback, which makes the GPT call in AI_ThreadSuggestion.tsx.

[Code](https://github.com/Yonom/assistant-ui/commit/cd186925f97ab83afa746858a8d91d5f55c11ab0)

Results:
1. Efficient Rendering: The solution ensures that the suggestions are rendered efficiently, only when there are updates to the assistant messages without any UI glitches.
2. API Call Optimization: The debounce mechanism minimizes the number of API calls, resulting in only 2 API calls each time, saving cost and computation.

[After useMemo and Debounce - only 2 api calls](https://flonnect.com/video/4214025e60bd-46e7-b4ca-2932e13f4492)

Shoutout to @Yonom for the assistance.

**Comment by Yonom** [comment]
Thank you for this! I investigated a bit further:

React calls every useEffect twice during development mode - this is a bit annoying when you're paying for tokens and duplicate API calls are generated. I added a specific debounce for this, because the two useEffect calls happen inside the same macrotask

```ts
// do not send duplicate requests in React Strict Mode during development
if (process.env.NODE_ENV === "development") {
  if (debounceRef.current) return;
  debounceRef.current = true;
  setTimeout(() => {
    debounceRef.current = false;
  }, 0);
}
```
