### ISSUE TITLE
install assistant-ui

### ISSUE THREAD

**Issue by andrepatt** [Yonom/assistant-ui#663]
trying to install as per readme file

Step 1: Create a new project with assistant-ui pre-configured:
npx assistant-ui@latest create my-app
cd my-app
Step 2: Update the .env file with your OpenAI API key.

Step 3: Run the app:
npm run dev

I get 
Error: spawn npx ENOENT
other-package-script process exited with code -4058

How should I proceed to install this? it's the whole code of the assistant ui site?
A more detailed README file would be optimal for someone not as experienced as me

Thanks!

**Comment by Yonom** [comment]
Is this issue resolveD?

**Comment by OlegSharov1** [comment]
I still get this error when trying to npx assistant-ui@latest create my-app.

**Comment by Yonom** [comment]
@OlegSharov1 could you paste the output of the following command:

`npx next info`

**Comment by Jey-Alt** [comment]
experiencing same issue on windows as well

**Comment by Yonom** [comment]
@Jey-Alt could you paste the output of the following command:

`npx next info`

**Comment by Jey-Alt** [comment]
This is my output:

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 15579
  Available CPU cores: 16
Binaries:
  Node: 20.12.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.9 // Latest available version is detected (14.2.9).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
  
  
  It does say npm is N/A but I did npm -v in the same directory and output: 10.8.3

**Comment by Yonom** [comment]
Thank you @andrepatt and @Jey-Alt for bringing up this issue. Thank you @Endi0n for the fix!

This should be solved now
