### ISSUE TITLE
Unable to Edit in Playground (New)

### ISSUE THREAD

**Issue by charliemday** [Yonom/assistant-ui#683]
I don't seem to be able to edit anything in the new version of the Playground (Not a blocking issue as I can just use the old version).

**Comment by Yonom** [comment]
Thanks for filing this! I'm unfortunately unable to reproduce the issue in the `examples/with-playground` project...

Perhaps something related to your particular usage of the playground broke. Are you using anything to programmatically set the playground state?

It would also be great to provide the exact version where the problem DOES NOT occur and the exact version where the problem DOES occur

Thanks!

**Comment by Yonom** [comment]
Just released a new version of @assistant-ui/react (v0.5.32) & @assistant-ui/playground (v0.0.19)
@charliemday can you test with these latest versions and report back? Thanks!

**Comment by charliemday** [comment]
Seems to be editable again now, thanks!
