### ISSUE TITLE
How to fetch the chat history, Using Custom Rest Provider

### ISSUE THREAD

**Issue by duwscan** [Yonom/assistant-ui#701]
i'm using Rest Customer Provider. User have chat thread, how can i implement the history chat feature ?

**Comment by Yonom** [comment]
Hey, the `useLocalRuntime` accepts a `initialMessages` array of messages, which you can use to provide the chat history

**Comment by da-cweb-dev** [comment]
> Hey, the `useLocalRuntime` accepts a `initialMessages` array of messages, which you can use to provide the chat history
> 
> 

Thanks, but there is no way to re set the intial messeage in the component. I need load more button btw

**Comment by Rajaniraiyn** [comment]
@da-cweb-dev https://github.com/Yonom/assistant-ui/pull/679#issuecomment-2295386156 will be helpful if you want to reset

**Comment by Yonom** [comment]
## Updating InitialMessages

@da-cweb-dev `@assistant-ui/react@0.5.37` adds a new method to runtime: `runtime.reset` which lets you re-set the initialMessages

## Pagination

I have added message pagination / load more button support to the list of TODOs.

You can already implement this:
1. add a custom `<LoadMore />` button to the top of message list:

```ts
const MyThread: FC<ThreadConfig> = (config) => {
  return (
    <Thread.Root config={config}>
      <Thread.Viewport>
        <ThreadWelcome />
        <LoadMore /> //add
        <Thread.Messages />
        <Thread.ViewportFooter>
          <Thread.ScrollToBottom />
          <Composer />
        </Thread.ViewportFooter>
      </Thread.Viewport>
    </Thread.Root>
  );
};
```

```ts
const { useRuntime } = useAssistantContext();

const handlePress = () => {
  const newMessages = await loadMore();
  const runtime = useRuntime.getState() as LocalRuntime;
  runtime.reset({ initialMessages: [...newMessages, ...runtime.thread.messages] });
}

return <button onPress={handlePress} />
```

**Comment by jpetrantoni** [comment]
Is there a way to pass ui content as message history?

**Comment by Yonom** [comment]
@jpetrantoni you would probably want to map tool calls to custom UI and you can pass the tool calls to message history
See "Tool UI" in the docs
