### ISSUE TITLE
403 Forbidden connection error for LangGraph Cloud API 

### ISSUE THREAD

**Issue by kbatsuren** [Yonom/assistant-ui#830]
The instruction for LangGraph cloud:
https://www.assistant-ui.com/docs/runtimes/langgraph

The current instructions don't mention where to configure the x-api-key of LangGraph Cloud API. 
https://langchain-ai.github.io/langgraph/cloud/reference/api/api_ref/

The network error persists as:
![image](https://github.com/user-attachments/assets/e1e5b7fc-0b49-4d00-8acd-65e295242f99)

**Comment by Yonom** [comment]
Thanks for catching this! Updating docs...
