### ISSUE TITLE
feature: Trieve integration

### ISSUE THREAD

**Issue by skeptrunedev** [Yonom/assistant-ui#880]
- [x] feature: hover state for markdown style `[^n]` citations 
  - [x] with link imperative integration for transforming highest level heading in sanitized innerHtml replace into an anchor with the link on the chunk
- [x] feature: ability for user to specify array of tags which informs some tabMenu style UI for flipping between them. `tag` selection should be used on a `must { "field": "tag_set", match_all: [tag] }` filter
- [x] feature: empty state should use the `get_suggested_queries` route to show users options for searching; 
  - [x] this should have a refresh button (allow hard-coding)
- [x] feature: followup suggestions should use `get_suggested_queries` route (allow hard-coding)
- [x] feature: when a citation is hovered over or clicked, send the CTR data

**Comment by Yonom** [comment]
- [ ] Switch to trieve TS sdk
- [ ] Move repo to monorepo
