### ISSUE TITLE
Include attachments prop in the useExternalMessageConverter

### ISSUE THREAD

**Issue by juagonala** [Yonom/assistant-ui#897]
I'm trying to add support to upload attachments to the Vercel Assistant integration, so I'm using the `useExternalMessageConverter` to convert the messages from the AI SDK to the ThreadMessage objects, and viceversa.

The issue I found is that on user messages, the function `joinExternalMessages()` only returns the `role`, and `content` props, ignoring the `attachments` prop. This is the line: https://github.com/Yonom/assistant-ui/blob/1b5720be665fb595d53b0aa8e0f16cf840a70e32/packages/react/src/runtimes/external-store/external-message-converter.tsx#L71

Please, update this piece of code to add support to the `attachments` property in the user messages.

Many thanks for you amazing work!

**Comment by Yonom** [comment]
Thank you for catching this!

fixed in `@assistant-ui/react@0.5.66`
