### ISSUE TITLE
HTTP 201 status code not handled correctly

### ISSUE THREAD

**Issue by JeremyFabrikapp** [Yonom/assistant-ui#910]
Hi ! I'm laying around with assistant-ui, and wrap it into a custom package.

I noticed an issue, triggering an error while Api Response code is 201.

The current implementation only considers status code 200 as successful. However, HTTP 201 (Created) is also a valid success code, often returned when a new resource is created. This should be handled to avoid throwing unnecessary errors.

### Current behavior
Throws an error for status code 201.

### Expected behavior
Accept both 200 and 201 as successful status codes. But maybe is it voluntary 

### Suggested fix
Change the condition to check for result.ok or successful status codes (2xx range) instead of just 200

<img width="708" alt="image" src="https://github.com/user-attachments/assets/0e4906e7-c707-4264-8cd9-64fef57f42bf">

I'll be doing a few tests and pushing a PR, thanks for your clean work @Yonom !

Edit : Well after thoughts, that would apply to ApiRuntime not EdgeRuntime, feel free to close issue in that case !

**Comment by Yonom** [comment]
Thank you, I agree with this being a potential issue, although we havent faced it anywhere yet

Happy to accept a change of the check to `!result.ok`

**Comment by Yonom** [comment]
Fixed
