### ISSUE TITLE
An issue in building your components in my project.

### ISSUE THREAD

**Issue by GQAdonis** [Yonom/assistant-ui#933]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@assistant-ui/react-markdown@0.2.18` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@assistant-ui/react-markdown/dist/tailwindcss/index.mjs b/node_modules/@assistant-ui/react-markdown/dist/tailwindcss/index.mjs
index b2378c5..e51d294 100644
--- a/node_modules/@assistant-ui/react-markdown/dist/tailwindcss/index.mjs
+++ b/node_modules/@assistant-ui/react-markdown/dist/tailwindcss/index.mjs
@@ -1,5 +1,5 @@
 // src/tailwindcss/index.ts
-import plugin from "tailwindcss/plugin";
+import plugin from "tailwindcss/plugin.js";
 var auiPlugin = plugin.withOptions(() => ({ addComponents }) => {
   addComponents({
     '@import "@assistant-ui/react-markdown/styles/tailwindcss/markdown.css"': ""
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Yonom** [comment]
What bundler do you use? What is your tsconfig?

Can you output the tsconfig.ts file?
