### ISSUE TITLE
Latest react-markdown package does not work for primitives

### ISSUE THREAD

**Issue by thedaiga** [Yonom/assistant-ui#939]
I ran into an issue where the following didn't work with version 0.2.18.  I downgraded to 0.2.13 and it worked.

import { makeMarkdownText } from "@assistant-ui/react-markdown";

 const MarkdownText = makeMarkdownText();

 <AssistantMessage.Content components={{ Text: MarkdownText }} />

**Comment by Yonom** [comment]
hey, what version of @assistant-ui/react do you have installed? make sure you are using the latest version (0.5.70)

What error are you getting?
