### ISSUE TITLE
RSC example app appears to be broken

### ISSUE THREAD

**Issue by ydesouza** [Yonom/assistant-ui#943]
**Repro steps:**
1. Navigate to https://assistant-ui-rsc-example.vercel.app or "Tool UI" example.
2. Interact with chat or click on one of the suggestions, "List flights flying from San Francisco to Rome today" or "What is the status of flight BA142?"

**Expected:**
Appropriate UI widget is displayed

**Actual:**
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 865437001

**Comment by Yonom** [comment]
@ydesouza thank you for reporting this, I have fixed this now - this was a dependency mismatch issue
