### ISSUE TITLE
ThreadMessageLike.tsx (Line 66) --> TypeError: part.text.trim is not a function. (In 'part.text.trim()', 'part.text.trim' is undefined)

### ISSUE THREAD

**Issue by GregorBeuster** [Yonom/assistant-ui#962]
I tried to make assistant ui work with a sample repo from Langgraph (memory-agent) and it doesnt work. The issue seems to be that when I bin a tool to the model in Langgraph the response content of the assistant message looks like this:

`content: [{text: "Sounds", type: "text", index: 0}] (1)` --> that causes the error you see in the title of this issue.

BUT when I use the same exact graph but with a model without tools like this: llm.invoke(...) instead of llm.bindTools(...).invoke, the response content looks like this:

`content: "Sounds great, I'd love to hear about your upcoming travel plans! As an AI assistant without a physical form, I don't actually have trave…"` --> NOT causing any error in assistant ui

I don´t know why the content is an array after binding tools to the model, but could you please just test assistant ui with any sample Langgraph repo using tools!

**Comment by Yonom** [comment]
Thank you for reporting this @GregorBeuster 

Please upgrade to the latest version of @assistant-ui/react and @assistant-ui/react-langgraph for the fix
