### ISSUE TITLE
Persisting problem with complex message conten using LangGraph example code!

### ISSUE THREAD

**Issue by GregorBeuster** [Yonom/assistant-ui#979]
Despite updating to latest version I still get:

`TypeError: part.text.trim is not a function. (In 'part.text.trim()', 'part.text.trim' is undefined)` 

...when using the memory-agent example from Langgraph. I think it´s this code not beeing compatible with complex message content:

`// src/runtimes/external-store/ThreadMessageLike.tsx
var fromThreadMessageLike = (like, fallbackId, fallbackStatus) => {
  const { role, id, createdAt, attachments, status } = like;
  const common = {
    id: id ?? fallbackId,
    createdAt: createdAt ?? /* @__PURE__ */ new Date()
  };
  const content = typeof like.content === "string" ? [{ type: "text", text: like.content }] : like.content;
  if (role !== "user" && attachments)
    throw new Error("Attachments are only supported for user messages");
  switch (role) {
    case "assistant":
      return {
        ...common,
        role,
        content: content.map((part) => {
          const type = part.type;
          switch (type) {
            case "text":
              if (part.text.trim().length === 0) return null;
              return part;
            case "ui":
              return part;
            case "tool-call": {
              if ("argsText" in part) return part;
              return {
                ...part,
                argsText: JSON.stringify(part.args)
              };
            }
            default: {
              const unhandledType = type;
              throw new Error(`Unknown content part type: ${unhandledType}`);
            }
          }
        }).filter((c) => !!c),
        status: status ?? fallbackStatus
      };`

As LangGraph returns content like this when tools are bound, even if there is no tool call involved:

`content: [{text: "Natürlich!", type: "text", index: 0}]`

It seems only `text` content is supported for `assistant` messages?!

**Comment by Yonom** [comment]
@GregorBeuster so sorry to have missed this! thanks for reporting it again

**Comment by Yonom** [comment]
hopefully finally fixed in v0.0.15, let me know if you still encounter issues!
