### ISSUE TITLE
Example of markdown with streamUI? 

### ISSUE THREAD

**Issue by mattlanham** [Yonom/assistant-ui#980]
Any chance you can provide an example of having a tool response rendered as markdown? 

The only way I can get this to work at the moment is using the Markdown plugin directly within the generate function, I have set the `components={{ Text: MarkdownText }}` in the Thread.tsx, but the tool responses seem to always render in plain text unless I use the plugin directly.

I can't seem to get the partials rendering markdown either, so hopefully there's a better way to just have any text returned rendered as markdown in a message?

Here's code I have that does render markdown (not including the partials being yield):

```
const result = await streamUI({
    model: openai("gpt-4o"),
    messages: [...history.get(), { role: "user", content: input }],
    text: ({ content, done }) => {
      if (done) {
        history.done((messages: ServerMessage[]) => [...messages, { role: "assistant", content }]);
      }

      return <Markdown remarkPlugins={[remarkGfm]}>{content}</Markdown>;
    },
    tools: {
      lookup_question: {
        description: "Lookup a question in the knowledge base",
        parameters: z.object({
          question: z.string().describe("The question to lookup"),
        }),
        generate: async function* ({ question }) {
          const answer = yield* generateAnswer(question, history);
          history.done((messages: ServerMessage[]) => [...messages, { role: "assistant", content: answer }]);
          return <Markdown remarkPlugins={[remarkGfm]}>{answer}</Markdown>;
        },
      },
    },
  });
```

**Comment by Yonom** [comment]
Hey, in RSC mode, you are responsible for rendering the entire message content - assistant-ui receives UI content as opaque ReactNodes and cannot really help you much there

The following may or may not work, I haven't tested this yet. 
Can you help by trying it out?

```ts
<TextContentPartProvider text={answer}><MarkdownText /></TextContentPartProvider>
```

and if you want to show the loading "dot" while loading:

```ts
<TextContentPartProvider text={answer} isLoading><MarkdownText /></TextContentPartProvider>
```

keep in mind that this approach streams the entire markdown content over and over as more chunks are streamed (quadradic bandwidth usage), it's a limitation of the Vercel AI SDK RSC (see: https://sdk.vercel.ai/docs/getting-started/navigating-the-library#when-to-use-ai-sdk-rsc)

I hope this helps!

**Comment by Yonom** [comment]
@mattlanham  Closing this, feel free to reopen if you are still facing issues!

**Comment by madarco** [comment]
Hi!

Thanks for the great library. I'm facing the same issue, and tried this:
```
ui.update(
  <TextContentPartProvider text={content}>
    <MarkdownText />
  </TextContentPartProvider>
);
```

But sadly I get this error and I'm not sure how to fix it:

```
import { createContextStoreHook } from "../../context/react/utils/createContextStoreHook.mjs";
  11 | import { jsx } from "react/jsx-runtime";
> 12 | var SmoothContext = createContext(null);
     |                                  ^
  13 | var makeSmoothContext = (initialState) => {
  14 |   const useSmoothStatus2 = create(() => initialState);
  15 |   return { useSmoothStatus: useSmoothStatus2 };
  ```

**Comment by Yonom** [comment]
Vercel has marked RSC as experimental, and are suggesting new projects to use AI SDK UI and existing RSC projects to migrate to AI SDK UI
https://sdk.vercel.ai/docs/ai-sdk-rsc/migrating-to-ui

I am closing this issue as wont-fix; an existing implementation of RSC with markdown streaming support can be found here:
https://github.com/yonom/assistant-ui-rsc-example
