### ISSUE TITLE
Still problems with Langgraph tool use example... Error: Unknown content part type: [object Object]

### ISSUE THREAD

**Issue by GregorBeuster** [Yonom/assistant-ui#992]
[
  {
    "content": "merk dir dass 1,92m gross bin",
    "additional_kwargs": {},
    "response_metadata": {},
    "type": "human",
    "name": null
  },
  {
    "content": **Array**, **<-- THIS COULD BE THE NEW PROBLEM?**
    "additional_kwargs": {},
    "response_metadata": {
      "stop_reason": "tool_use",
      "stop_sequence": null
    },
    "type": "ai",
    "name": null
  },
  {
    "content": "Stored memory None",
    "additional_kwargs": {},
    "response_metadata": {},
    "type": "tool",
    "name": null
  },
  {
    "content": [
      {
        "text": "↵↵Vielen Dank für diese Information!",
        "type": "text",
        "index": 0
      }
    ],
    "additional_kwargs": {},
    "response_metadata": {
      "stop_reason": "end_turn",
      "stop_sequence": null
    },
    "type": "ai",
    "name": null
  }
]

When I try to display this thread containing 4 messages, I don´t get the error regaring trim function not defined anymore but a new one:

`Error: Unknown content part type: [object Object]`... 

<img width="1878" alt="Screenshot 2024-10-13 at 9 08 42 AM" src="https://github.com/user-attachments/assets/7ffe57ea-e3d2-4bb9-a631-abf92e8dc8c9">

<img width="652" alt="Screenshot 2024-10-13 at 9 12 33 AM" src="https://github.com/user-attachments/assets/046ed691-4fb7-4981-8b3a-75149feb17a8">

**Comment by Yonom** [comment]
Thanks. Hmmm... there is a bug in the error message code, which is why you're seeing [object Object]

I have fixed the bug, so if you upgrade, we will see the correct error message.

Could you `console.log(JSON.stringify(values, null, 2))` so that we see what's inside the mysterious Array? Somewhere inside of this array, there is an unrecognized `type`

**Comment by Yonom** [comment]
So it's the "tool_use" content part that is confusing `assistant-ui` - thanks for catching this! 

Just fixed in #992 /  @assistant-ui/react-langgraph v0.0.18

Can you confirm that this is fixed? Thanks a lot and sorry about the back and forth!

**Comment by Yonom** [comment]
Amazing :)
